user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
	path('signup/1/', views.account_signup, name="signup_1"),
	path('signup/2/', views.add_info, name="signup_2"),
	path('signup/3/', views.give_feedback, name="signup_3"),
	path('signup/google/', views.signup_with_google, name="signup_google"),
	path('get/user/<str:type>/', views.user_auth),
	path('create/account/', views.create_account),
	path('create/user/google/', views.create_google_user),
	path('profile/', views.profile, name="profile"),
	path('login/', views.login, name="login"),
	path('logout/', views.logout, name="logout"),
	path('events/', views.event_list, name="show_events"),
]

web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("landing.urls")),
    path('user/', include("user.urls")),
    path('news/', include("news.urls")),
    path('events/', include("events.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/models.py
from django.db import models

NAME_LENGTH = 50
roles = (
	("Admin", "Admin"),
	("Participant", "Participant"),
	)

genders = (
	("Male", "Male"),
	("Female", "Female"),
	)

class User(models.Model):
	google_user_id = models.CharField(blank=True, null=True, max_length=300)
	username = models.CharField(max_length=NAME_LENGTH)
	full_name = models.CharField(max_length=NAME_LENGTH, blank=True, null=True)
	gender = models.CharField(max_length=NAME_LENGTH, choices=genders, blank=True, null=True)
	date = models.DateField(blank=True, null=True)
	home_address = models.TextField(max_length=300, blank=True, null=True)
	role = models.CharField(max_length=NAME_LENGTH, choices=roles, blank=True, null=True)
	email = models.EmailField(max_length=NAME_LENGTH)
	password = models.CharField(max_length=NAME_LENGTH)
	events = models.TextField(blank=True, null=True)
	news = models.TextField(blank=True, null=True)
	# def __str__(self):
	# 	return self.username

user/forms.py
from django import forms
from . import models

class UserForm1(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={
			"class": "username",
			"onkeyup": "usernameValidation()",
			"placeholder": "Username",
			"data-type": "username",
		}))
	email = forms.EmailField(widget=forms.EmailInput(attrs={
			"class": "",
			"placeholder": "Email",
			"data-type": "email",
		}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={
			"class": "password",
			"onkeyup": "matchPassword()",
			"placeholder": "Password",
			"minlength": "8",
			"data-type": "password",
		}))
	role = forms.CharField(widget=forms.Select(choices=models.roles, attrs={
			"class": "",
			"placeholder": "Role",
			"data-type": "role",
		}))

class UserForm2(forms.Form):
	full_name = forms.CharField(widget=forms.TextInput(attrs={
			"class": "",
			"placeholder": "Full Name",
		}))
	gender = forms.CharField(widget=forms.Select(choices=models.genders, attrs={
			"class": "",
			"placeholder": "Gender",
		}))
	date = forms.DateField(widget=forms.DateInput(attrs={
			"class": "",
			"type": "date",
			"placeholder": "Date",

		}))
	home_address = forms.CharField(widget=forms.Textarea(attrs={
			"class": "",
			"placeholder": "Home Address",
		}))

class LoginForm(forms.Form):
	type = "login"
	username = forms.CharField(widget=forms.TextInput(attrs={
			"class": "",
			"placeholder": "Username",
			"data-type": "username",
		}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={
			"class": "",
			"placeholder": "Password",
			"data-type": "password",
		}))

class GoogleLoginForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={
			"class": "",
			"placeholder": "Username",
			"data-type": "username",
		}))
	role = forms.CharField(widget=forms.Select(choices=models.roles, attrs={
			"class": "",
			"placeholder": "Role",
			"data-type": "role",
		}))

user/views.py
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, JsonResponse
from google.oauth2 import id_token
from google.auth.transport import requests
from user import forms, models
from events.models import Events
from news.models import News
import json
CLIENT_ID = "729005614615-auunri0f7584kro5tqegru8mm9618th4.apps.googleusercontent.com"
# Create your views here.
def get_user_by_username(username):
	user = models.User.objects.filter(username=username).first()
	return user

def get_user_by_email(email):
	user = models.User.objects.filter(email=email).first()
	return user


def account_signup(request):
	# try:
	# 	request.session["user_is_exist"]
	# 	return redirect("landing:landing_page")
	# except KeyError:
	# 	request.session["last_visited"] = request.META.get('HTTP_REFERER')
	data = {
		"form": forms.UserForm1(),
		"message": "",
	}
	return render(request, "main-pages/signup-1.html", data)

def create_account(request):
	data = {
		"success": False,
		"username_exists": False,
		"email_exists": False,
		"next_page": False,
		"done": False,
	}

	if request.method == "POST":
		form = forms.UserForm1(request.POST)
		if form.is_valid():
			user_1 = get_user_by_username(request.POST["username"].lower())
			user_2 = get_user_by_email(request.POST["email"].lower())
			if user_1 == None and user_2 == None:
				if request.POST["role"] == "Admin":
					request.session["username"] = request.POST["username"].lower()
					request.session["email"] = request.POST["email"].lower()
					request.session["password"] = request.POST["password"]
					request.session["role"] = request.POST["role"]
					data["next_page"] = True
				else:
					create_user(
						"",
						request.POST["username"],
						"",
						"",
						None,
						"",
						request.POST["email"],
						request.POST["password"],
						request.POST["role"]
					)
					data["done"] = True
				data["success"] = True
			else:
				if (user_1 != None and user_2 != None):
					data["username_exists"] = True
					data["email_exists"] = True
				elif (user_2 == None):
					data["username_exists"] = True
				else:
					data["email_exists"] = True

	return JsonResponse(data)

def add_info(request):
	if request.method == "POST":
		form = forms.UserForm2(request.POST)
		if form.is_valid():
			create_user(
				"",
				request.session["username"],
				form.cleaned_data["full_name"],
				form.cleaned_data["gender"],
				form.cleaned_data["date"],
				form.cleaned_data["home_address"],
				request.session["email"],
				request.session["password"],
				request.session["role"]
			)
			del request.session["username"]
			del request.session["email"]
			del request.session["password"]
			del request.session["role"]
			return redirect("user:signup_3")
	else:
		data = {
			"form": forms.UserForm2()
		}
		return render(request, "main-pages/signup-2.html", data)

def give_feedback(request):
	data = {}
	return render(request, "main-pages/signup-3.html", data)

def create_google_user(request):
	data = {
		"success": False,
	}
	if request.method == "POST":
		form = forms.GoogleLoginForm(request.POST)
		if form.is_valid():
			create_user(
				request.session["user_id"],
				request.POST["username"].lower(),
				"",
				"Male",
				None,
				"",
				"",
				"",
				request.POST["role"]
			)
			del request.session["user_id"]
			request.session["user_exists"] = True
			request.session["username"] = request.POST["username"].upper()
			request.session["role"] = request.POST["role"]
			data["success"] = True
	return JsonResponse(data)

def create_user(google_id, username, name, gender, date, home_address, email, password, role):
	user = models.User(
		google_user_id=google_id,
		username=username,
		full_name=name,
		gender=gender,
		date=date,
		home_address=home_address,
		email=email,
		password=password,
		role=role,
		events="",
		news=""
		)
	user.save()
	return user


def login(request):
	data = {
		"form": forms.LoginForm()
	}
	return render(request, "main-pages/login.html", data)

def user_auth(request, type):
	data = {
		"user_exists": False
	}
	if request.method == "POST":
		form = forms.LoginForm(request.POST)
		if type == "google":
			userid = get_google_user_id(request.POST["token_id"])
			user = models.User.objects.all().filter(google_user_id = userid).first()
			if user != None:
				data["user_exists"] = True
				request.session["user_exists"] = True
				request.session["username"] = user.username.upper()
				request.session["role"] = user.role
			else:
				request.session["user_id"] = userid

		elif form.is_valid():
			username = form.cleaned_data["username"].lower()
			password = form.cleaned_data["password"]
			user = get_user_by_username(username)
			if user != None:
				if password == user.password:
					data["user_exists"] = True
					request.session["user_exists"] = True
					request.session["username"] = user.username.upper()
					request.session["role"] = user.role

		try:
			data["last_visited"] = request.session["last_visited"]
		except KeyError:
			data["last_visited"] = "/home/"
	return JsonResponse(data)

def get_google_user_id(token):
    try:
        # Specify the CLIENT_ID of the app that accesses the backend:
        idinfo = id_token.verify_oauth2_token(token, requests.Request(), CLIENT_ID)

        # Or, if multiple clients access the backend server:
        # idinfo = id_token.verify_oauth2_token(token, requests.Request())
        # if idinfo['aud'] not in [CLIENT_ID_1, CLIENT_ID_2, CLIENT_ID_3]:
        #     raise ValueError('Could not verify audience.')

        if idinfo['iss'] not in ['accounts.google.com', 'https://accounts.google.com']:
            raise ValueError('Wrong issuer.')

        # If auth request is from a G Suite domain:
        # if idinfo['hd'] != GSUITE_DOMAIN_NAME:
        #     raise ValueError('Wrong hosted domain.')

        # ID token is valid. Get the user's Google Account ID from the decoded token.
        userid = idinfo['sub']
        return userid
    except ValueError:
        # Invalid token
        return None


def logout(request):
	data = dict()
	try:
		del request.session["user_exists"]
		del request.session["username"]
		del request.session["role"]
		data["success"] = True
	except KeyError:
		data["success"] = False
	return JsonResponse(data)

def profile(request):
	data = {}
	return render(request, "main-pages/profile.html", data)

def signup_with_google(request):
	form = forms.GoogleLoginForm()
	data = {
		"form": form,
	}
	return render(request, "main-pages/signup-google.html", data)

def event_list(request):
	data = {
		"success": False,
		"events_list": dict(),
	}
	if request.method == "POST":
		found = models.User.objects.filter(username=request.session["username"].lower()).first()
		if found.events != "":
			data["success"] = True
			for i in found.events.split(";")[:-1]:
				obj = Events.objects.filter(id = i).first()
				now = obj.date.date()
				data["events_list"][obj.event_name] = [obj.event_name, str(now)]
	data_json = json.dumps(data)
	return HttpResponse(data_json, content_type="application/json")

user/templates/main-pages/login.html
{% load static %}

<!DOCTYPE HTML>
<html>
<head>
	<title>Login??</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="google-signin-client_id" content="729005614615-auunri0f7584kro5tqegru8mm9618th4.apps.googleusercontent.com">
	<link rel="shortcut icon" type="image/x-icon" href="/media/icons/favicon.ico/" />
	<link href="https://fonts.googleapis.com/css?family=Raleway:500,900" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Concert+One" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/user-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/button-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/navbar-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/image-style.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.js'%}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
	<script src="https://apis.google.com/js/platform.js" async defer></script>
	<script type="text/javascript" src="{% static 'js/login-script.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/navbar-script.js' %}"></script>
</head>
<body>
	<div class="grid-container">
		<div class="grid-item-1">
			<div class="image-2-asset image-2-format"></div>
			<div class="image-5-asset image-5-format"></div>
		</div>
		<div class="grid-item-2">
			{% include "reusable-pages-user/navbar-base.html" %}
		</div>
		<div class="grid-item-4">
			<form action="" method="POST">
				{% csrf_token %}
				<div class="user-con">
					<div class="user-icon"></div>
					{{ form.username }}
				</div>
				<div class="password-con">
					<div class="user-icon"></div>
					{{ form.password }}
				</div>
				<div class="submit-con">
					<input type="submit" name="submit" value="Login">
				</div>
				<label>Or login with</label>
				<div class='g-signin2' data-onsuccess='onSignIn'></div>
			</form>
		</div>
		<div class="grid-item-5">
			<p id="message"></p>
		</div>
	</div>
</body>
</html>

user/templates/main-pages/profile.html
{% load static %}

<!DOCTYPE HTML>
<html>
<head>
	<title>Login??</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="google-signin-client_id" content="729005614615-auunri0f7584kro5tqegru8mm9618th4.apps.googleusercontent.com">
	<link rel="shortcut icon" type="image/x-icon" href="/media/icons/favicon.ico/" />
	<link href="https://fonts.googleapis.com/css?family=Raleway:500,900" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Concert+One" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/user-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/button-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/navbar-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/image-style.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.js'%}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
	<script src="https://apis.google.com/js/platform.js?onload=onLoad" async defer></script>
	<script type="text/javascript" src="{% static 'js/login-script.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/navbar-script.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/profile-script.js' %}"></script>
</head>
<body>
    <div class="grid-container">
        <div class="grid-item-1">
            <div class="image-2-asset image-2-format"></div>
            <div class="image-5-asset image-5-format"></div>
        </div>
        <div class="grid-item-2">
            {% include "reusable-pages/navbar-base.html" %}
        </div>
        <div class="grid-item-4">
			<label>My Events</label>
			<table class="table table-dark">
		        <thead>
		          <tr>
		            <th scope="col">Event Name</th>
		            <th scope="col">Date</th>
		          </tr>
		        </thead>
		        <tbody id="content">
		        </tbody>
		    </table>
        </div>
        <div class="grid-item-5">
            <p id="message"></p>
        </div>
    </div>
</body>
</html>

user/templates/main-pages/signup-1.html
{% load static %}

<!DOCTYPE HTML>
<html>
<head>
	<title>Sign Up!!</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" type="image/x-icon" href="/media/icons/favicon.ico/" />
	<link href="https://fonts.googleapis.com/css?family=Raleway:500,900" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Concert+One" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/user-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/button-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/navbar-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/image-style.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.js'%}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
	<script type="text/javascript" src="{% static 'js/signup-1-script.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/navbar-script.js' %}"></script>
</head>
<body>
	<div class="grid-container">
		<div class="grid-item-1">
			<div class="image-2-asset image-2-format"></div>
			<div class="image-5-asset image-5-format"></div>
		</div>
		<div class="grid-item-2">
			{% include 'reusable-pages-user/navbar-base.html' %}
		</div>
		<div class="grid-item-3">
			<div class="process">
				<a href="{% url 'user:signup_1' %}">
					<div class="circle mark">
						<label>
							Create Account
						</label>
					</div>
				</a>
				<div class="line"></div>
				<div class="circle">
					<label>
						Add Information
					</label>
				</div>
				<div class="line"></div>
				<div class="circle">
					<label>
						Finish
					</label>
				</div>
			</div>
		</div>
		<div class="grid-item-4">
			<form action="" method="POST">
				{% csrf_token %}
				<div class="user-con">
					<div class="box-icon icon-format user-icon"></div>
					{{ form.username }}
				</div>
				<div class="email-con">
					<div class="box-icon icon-format email-icon"></div>
					{{ form.email }}
				</div>
				<div class="password-con">
					<div class="box-icon icon-format password-icon"></div>
					{{ form.password }}
					<div class="icon-format chain-icon"></div>
					<input type="password" class="password" placeholder="Confirm password" minlength="8" name="password" onkeyup="matchPassword()">
				</div>
				<div class="role-con">
					<div class="box-icon icon-format role-icon"></div>
					{{ form.role }}
				</div>
				<div class="submit-con">
					<input class="button-submit button-disable" type="submit" value="Create">
				</div>
			</form>
		</div>
		<div class="grid-item-5">
			<p id="message"></p>
		</div>
	</div>
</body>
</html>

user/templates/main-pages/signup-2.html
{% load static %}

<!DOCTYPE HTML>
<html>
<head>
	<title>Sign Up!!</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" type="image/x-icon" href="/media/icons/favicon.ico/" />
	<link href="https://fonts.googleapis.com/css?family=Raleway:500,900" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Concert+One" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/user-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/button-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/navbar-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/image-style.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.js'%}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
	<script type="text/javascript" src="{% static 'js/navbar-script.js' %}"></script>
</head>
<body>
	<div class="grid-container">
		<div class="grid-item-1">
			<div class="image-2-asset image-2-format"></div>
			<div class="image-5-asset image-5-format"></div>
		</div>
		<div class="grid-item-2">
			{% include 'reusable-pages/navbar-base.html' %}
		</div>
		<div class="grid-item-3">
			<div class="process">
				<a href="{% url 'user:signup_1' %}">
					<div class="circle mark">
						<label>
							Create Account
						</label>
					</div>
				</a>
				<div class="line mark"></div>
				<a href="{% url 'user:signup_2' %}">
					<div class="circle mark">
						<label>
							Add Information
						</label>
					</div>
				</a>
				<div class="line"></div>
				<div class="circle">
					<label>
						Finish
					</label>
				</div>
			</div>
		</div>
		<div class="grid-item-4">
			<form action="" method="POST">
				{% csrf_token %}
				<div class="name-con">
					<div class="box-icon icon-format user-icon"></div>
					{{ form.full_name }}
				</div>
				<div class="gender-con">
					<div class="box-icon icon-format gender-icon"></div>
					{{ form.gender }}
				</div>
				<div class="date-con">
					<div class="box-icon icon-format date-icon"></div>
					{{ form.date }}
				</div>
				<div class="home-con">
					<div class="box-icon icon-format home-icon"></div>
					{{ form.home_address }}
				</div>
				<div class="submit-con">
					<input type="submit" name="submit" value="Finish">
				</div>
			</form>
		</div>
		<div class="grid-item-5"></div>
	</div>
</body>
</html>

user/templates/main-pages/signup-3.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
	<title>Sign Up!!</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" type="image/x-icon" href="/media/icons/favicon.ico/" />
	<link href="https://fonts.googleapis.com/css?family=Raleway:500,900" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Concert+One" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/user-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/button-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/navbar-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/image-style.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.js'%}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
	<script type="text/javascript" src="{% static 'js/navbar-script.js' %}"></script>
</head>
<body>
	<div class="grid-container">
		<div class="grid-item-1">
			<div class="image-2-asset image-2-format"></div>
			<div class="image-5-asset image-5-format"></div>
		</div>
		<div class="grid-item-2">
			{% include 'reusable-pages/navbar-base.html' %}
		</div>
		<div class="grid-item-3">
			<div class="process">
				<div class="circle mark">
					<label>
						Create Account
					</label>
				</div>
				<div class="line mark"></div>
				<div class="circle mark">
					<label>
						Add Information
					</label>
				</div>
				<div class="line mark"></div>
				<div class="circle mark">
					<label>
						Finish
					</label>
				</div>
			</div>
		</div>
		<div class="grid-item-4">
			<div class="feedback-con">
				<label class="feedback-word">
					Thanks for signing up to our project
				</label>
				<div class="icon-format handshake-icon"></div>
			</div>
		</div>
		<div class="grid-item-5"></div>
	</div>
</body>
</html>

user/templates/main-pages/signup-google.html
{% load static %}

<!DOCTYPE HTML>
<html>
<head>
	<title>Sign Up!!</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" type="image/x-icon" href="/media/icons/favicon.ico/" />
	<link href="https://fonts.googleapis.com/css?family=Raleway:500,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Concert+One" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/user-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/button-style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/navbar-style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/image-style.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.js'%}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
	<script type="text/javascript" src="{% static 'js/signup-google-script.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/navbar-script.js' %}"></script>
</head>
<body>
	<div class="grid-container">
		<div class="grid-item-1">
			<div class="image-2-asset image-2-format"></div>
			<div class="image-5-asset image-5-format"></div>
		</div>
		<div class="grid-item-2">
			{% include 'reusable-pages-user/navbar-base.html' %}
		</div>
		<div class="grid-item-3">
            <div class="process">
                <h1>One more step</h1>
            </div>
		</div>
		<div class="grid-item-4">
			<form>
				{% csrf_token %}
				<div class="user-con">
					<div class="box-icon icon-format user-icon"></div>
					{{ form.username }}
				</div>
				<div class="role-con">
					<div class="box-icon icon-format role-icon"></div>
                    {{ form.role }}
                </div>
                <div class="submit-con">
                    <input class="button-submit" type="submit" name="submit" value="Create">
                </div>
			</form>
		</div>
		<div class="grid-item-5">
			<p id="message"></p>
		</div>
	</div>
</body>
</html>