events/urls.py
from django.urls import path
from . import views

app_name = 'events'
urlpatterns = [
	path("", views.events_list, name = "events"),
	path("delete/<int:id>/", views.delete_events),
	path("check/user/", views.check_user),
	path("update/", views.update_event_user),
	path("participants/", views.show_participants),
]

landing/urls.py
from django.urls import path
from . import views

app_name = 'landing'
urlpatterns = [
	path('', views.landing_page, name="landing_page"),
	path('addComment/', views.add_comment, name='add_comment'),
	path('delete/<int:id>/', views.delete_comment),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
	path("", views.news_list, name="news"),
	path("delete/<int:id>/", views.delete_news),
	path("check/user/", views.check_user),
	path("update/", views.update_news_lover),
	path("lover/", views.show_lover),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
	path('signup/1/', views.account_signup, name="signup_1"),
	path('signup/2/', views.add_info, name="signup_2"),
	path('signup/3/', views.give_feedback, name="signup_3"),
	path('signup/google/', views.signup_with_google, name="signup_google"),
	path('get/user/<str:type>/', views.user_auth),
	path('create/account/', views.create_account),
	path('create/user/google/', views.create_google_user),
	path('profile/', views.profile, name="profile"),
	path('login/', views.login, name="login"),
	path('logout/', views.logout, name="logout"),
	path('events/', views.event_list, name="show_events"),
]

web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("landing.urls")),
    path('user/', include("user.urls")),
    path('news/', include("news.urls")),
    path('events/', include("events.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

landing/models.py
from django.db import models
from django.utils import timezone

class Comments(models.Model):
	message = models.TextField(max_length = 300, blank = False)
	created_at = models.DateTimeField(auto_now = True)
	name = models.CharField(max_length=50)

landing/forms.py
from django import forms
from .models import *

class Make_Comments(forms.ModelForm):
	class Meta:
		model = Comments
		fields = [
			"message",
		]
		widgets = {
			"message" : forms.Textarea(attrs = {'placeholder' : 'Hello User, Any Testimonies??', 'class' : 'formstyle'})
		}

	

landing/views.py
from django.shortcuts import render, redirect
from .models import Comments
from .forms import Make_Comments
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers

# Create your views here.

def landing_page(request):
	rsponse = {}
	form = Make_Comments(request.POST or None)
	comments = Comments.objects.all().order_by("-id")
	response = {
		"comments" : comments,
		"form" : form
	}
	return render(request, 'main-pages/landing.html', response)

def add_comment(request):
	response = {'status' : False}
	form = Make_Comments(request.POST)

	if(request.method == "POST"):
		if(form.is_valid()):
			message = request.POST["message"]
			comment = Comments(message = message, name = request.session["username"].lower())
			comment.save()
			response['status'] = True
			response['new_comment'] = [comment.message, comment.name, comment.created_at.date(), comment.id]

	return JsonResponse(response)

def delete_comment(request, id):
	if request.session["user_exists"]:
		comment = Comments.objects.filter(name = request.session["username"].lower(), id = id).first()
		if comment != None:
			comment.delete()
	return redirect("landing:landing_page")

landing/templates/reusable-pages/navbar-base.html
<div class="navbar-con">
	<div class="navbar-menu" onclick="showNavbar()">
		<div class="button button-navbar-size">	
			<div class="background-color-animated"></div>
			<div class="border-line-2"></div>
			<div class="border-line-3"></div>
			<div class="border-line-4"></div>
			<div class="text">
				MENU
			</div>
		</div>
	</div>
	<div class="grid-container-navbar navbar-init">
		<div class="grid-item-navbar-1">
			<a class="button-navbar-size" href="{% url 'landing:landing_page' %}">
				<div class="button button-navbar-size">	
					<div class="background-color-animated"></div>
					<div class="border-line-2"></div>
					<div class="border-line-3"></div>
					<div class="border-line-4"></div>
					<div class="text">
						HOME
					</div>
				</div>
			</a>

			<a class="button-navbar-size" href="{% url 'events:events' %}">
				<div class="button button-navbar-size">	
					<div class="background-color-animated"></div>
					<div class="border-line-2"></div>
					<div class="border-line-3"></div>
					<div class="border-line-4"></div>
					<div class="text">
						EVENTS
					</div>
				</div>
			</a>
			<a class="button-navbar-size" href="{% url 'news:news' %}">
				<div class="button button-navbar-size">	
					<div class="background-color-animated"></div>
					<div class="border-line-2"></div>
					<div class="border-line-3"></div>
					<div class="border-line-4"></div>
					<div class="text">
						NEWS
					</div>
				</div>
			</a>
		</div>
		<div class="grid-item-navbar-2">
		{% if request.session.user_exists %}
			<!-- <div class="button profile button-navbar-size" onclick="showProfileMenu()">	 -->
			<a href="{% url 'user:profile' %}">	
				<div class="button button-navbar-size">	
					<div class="profile-menu">
						{{ request.session.role }}
					</div>
					<div class="background-color-animated"></div>
					<div class="border-line-2"></div>
					<div class="border-line-3"></div>
					<div class="border-line-4"></div>
					<div class="text username-con">
						{{ request.session.username }}
					</div>
				</div>
			</a>
			<!-- </div> -->
			<a class="button-navbar-size" data-type="logout">
				<div class="button button-navbar-size">	
					<div class="background-color-animated"></div>
					<div class="border-line-2"></div>
					<div class="border-line-3"></div>
					<div class="border-line-4"></div>
					<div class="text">
						LOGOUT
					</div>
				</div>
			</a> 
		{% else %}
			<a class="button-navbar-size" href="{% url 'user:signup_1' %}">
				<div class="button button-navbar-size">	
					<div class="background-color-animated"></div>
					<div class="border-line-2"></div>
					<div class="border-line-3"></div>
					<div class="border-line-4"></div>
					<div class="text">
						SIGNUP
					</div>
				</div>
			</a>

			<a class="button-navbar-size" href="{% url 'user:login' %}">
				<div class="button button-navbar-size">	
					<div class="background-color-animated"></div>
					<div class="border-line-2"></div>
					<div class="border-line-3"></div>
					<div class="border-line-4"></div>
					<div class="text">
						LOGIN
					</div>
				</div>
			</a>
		{% endif %}
		</div>
	</div>
</div>